import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat} from "next/font/google";
import BottomNav from './components/BottomNav/BottomNav';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ['latin'], // Використовуйте 'latin' або інші набори символів, які потрібні
  weight: ['400', '500', '600', '700'], // Вкажіть потрібні ваги шрифту
  variable: '--font-montserrat', // CSS-змінна для Tailwind CSS
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        <div className="lg:flex">
          <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 lg:flex-1 lg:ml-[250px] font-montserrat">
            {children}
            <BottomNav />
          </main>
        </div>
      </body>
    </html>
  );
}
